version: "3.9"

networks:
  paulistense_network_private:
    driver: bridge
  paulistense_network_public:
    driver: bridge

services:
  paulistense_db:
    image: mysql:latest
    container_name: paulistense_db
    ports: #para teste
      - '3306:3306' #para teste
    networks:
      - paulistense_network_private
      - paulistense_network_public #para teste
    volumes:
      - './setup.sql:/docker-entrypoint-initdb.d/setup.sql'
    environment:
      - MYSQL_ROOT_PASSWORD=$BANCO_SENHA

  servico-notificacao:
    image: servico
    environment:
      DB_HOST: paulistense_db
    ports:
      - "8080:8080"
    networks:
      - paulistense_network_private
    depends_on:
      - paulistense_db