version: "3.9"

networks:
  paulistense_network_private:
    driver: bridge
  paulistense_network_public:
    driver: bridge

services:
  paulistense_db:
    image: mysql:latest
    container_name: paulistense_db
    ports: #para teste
      - '3306:3306' #para teste
    networks:
      - paulistense_network_private
      - paulistense_network_public #para teste
    volumes:
      - './setup.sql:/docker-entrypoint-initdb.d/setup.sql'
    environment:
      - MYSQL_ROOT_PASSWORD=$BANCO_SENHA

  servico_notificacao:
    image: servico_notificacao:0.0.1-SNAPSHOT
    command: ["./wait-for-it.sh", "paulistense_db:3306", "-t", "30", "--", "java", "-jar", "servico.jar"]
    environment:
      DB_HOST: paulistense_db
    networks:
      - paulistense_network_private
    depends_on:
      - paulistense_db