-- 1. Tabela
CREATE TABLE USUARIOS (
  ID             NUMBER PRIMARY KEY,
  NOME           VARCHAR2(255 CHAR),
  CPF            VARCHAR2(14 CHAR),
  LOGIN          VARCHAR2(255 CHAR) NOT NULL,
  SENHA          VARCHAR2(255 CHAR),
  ULTIMO_ACESSO  TIMESTAMP,
  IMAGEM         VARCHAR2(255 CHAR),
  USUARIO_ID     NUMBER,
  ATIVO CHAR(1) DEFAULT 'S',
  CONSTRAINT USUARIOS_LOGIN_UQ UNIQUE (LOGIN),
  CONSTRAINT USUARIOS_CPF_UQ UNIQUE (CPF),
  CONSTRAINT USUARIOS_ATIVO_CK CHECK (ATIVO IN ('S', 'N')),
  CONSTRAINT USUARIOS_USUARIO_FK FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS (ID)
);

-- 2. Índice para a chave estrangeira
CREATE INDEX USUARIOS_USUARIO_FK_IDX ON USUARIOS (USUARIO_ID);

-- 3. Sequence para simular AUTO_INCREMENT
CREATE SEQUENCE USUARIOS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 4. Trigger para preencher o ID automaticamente
CREATE OR REPLACE TRIGGER USUARIOS_TRG_ID
BEFORE INSERT ON USUARIOS
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT USUARIOS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
