-- Usuário administrador (sem pai)
INSERT INTO USUARIOS (
  ID, NOME, CPF, LOGIN, SENHA, ULTIMO_ACESSO, IMAGEM, USUARIO_ID, ATIVO
) VALUES (
  1, 'ADMINISTRADOR', '00000000000', 'admin', '123456', CURRENT_TIMESTAMP, NULL, NULL, 'S'
);

-- Usuário subordinado ao admin
INSERT INTO USUARIOS (
  ID, NOME, CPF, LOGIN, SENHA, ULTIMO_ACESSO, IMAGEM, USUARIO_ID, ATIVO
) VALUES (
  2, 'JOÃO SILVA', '12345678901', 'joao', 'senha123', CURRENT_TIMESTAMP, NULL, 1, 'S'
);
COMMIT;