-- 1. Tabela
CREATE TABLE SISTEMAS (
  ID           NUMBER PRIMARY KEY,
  NOME         VARCHAR2(100 CHAR) NOT NULL,
  DESCRICAO    VARCHAR2(100 CHAR),
  ATIVO CHAR(1) DEFAULT 'S',
  USUARIO_ID   NUMBER,
  CONSTRAINT SISTEMAS_NOME_UQ UNIQUE (NOME),
  CONSTRAINT SISTEMAS_ATIVO_CK CHECK (ATIVO IN ('S', 'N')),
  CONSTRAINT SISTEMAS_USUARIO_FK FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS (ID)
);

-- 2. Índice para a FK
CREATE INDEX SISTEMAS_USUARIO_FK_IDX ON SISTEMAS (USUARIO_ID);

-- 3. Sequence para simular AUTO_INCREMENT
CREATE SEQUENCE SISTEMAS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 4. Trigger para preencher o ID automaticamente
CREATE OR REPLACE TRIGGER SISTEMAS_ID_TRG
BEFORE INSERT ON SISTEMAS
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT SISTEMAS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
