--Tabela
CREATE TABLE SCHEDULERS (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    CRON_EXPR VARCHAR2(100) NOT NULL,
    ATIVO CHAR(1) DEFAULT 'S',
    LOCK_AT_MOST_FOR VARCHAR2(4) NOT NULL,
    LOCK_AT_LEAST_FOR VARCHAR2(4) NOT NULL,
    SISTEMA_ID NUMBER NOT NULL,
    CONSTRAINT SCHEDULERS_NOME_UK UNIQUE (NOME),
    CONSTRAINT SCHEDULERS_ATIVO_CK CHECK (ATIVO IN ('S', 'N')),
    CONSTRAINT SCHEDULERS_SISTEMA_FK FOREIGN KEY (SISTEMA_ID) REFERENCES SISTEMAS (ID)
);

-- Sequência manual
CREATE SEQUENCE SCHEDULERS_SEQ START WITH 1 INCREMENT BY 1;

--Gatilho
CREATE OR REPLACE TRIGGER SCHEDULERS_TRG_ID
BEFORE INSERT ON SCHEDULERS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SCHEDULERS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
