--Tabela
CREATE TABLE SCHEDULERS (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    CRON_EXPRESSION VARCHAR2(50) NOT NULL,
    ATIVO CHAR(1) DEFAULT 'S' NOT NULL,
    DESCRICAO VARCHAR2(500),
    ULTIMA_EXECUCAO TIMESTAMP,
    PROXIMA_EXECUCAO TIMESTAMP,
    CRIADO_EM TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ATUALIZADO_EM TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    LOCK_AT_MOST_FOR VARCHAR2(4) NOT NULL,
    LOCK_AT_LEAST_FOR VARCHAR2(4) NOT NULL,
    SISTEMA_ID NUMBER NOT NULL,
    USUARIO_ID   NUMBER,
    CONSTRAINT SCHEDULERS_NOME_UK UNIQUE (NOME),
    CONSTRAINT SCHEDULERS_ATIVO_CK CHECK (ATIVO IN ('S', 'N')),
    CONSTRAINT SCHEDULERS_SISTEMA_FK FOREIGN KEY (SISTEMA_ID) REFERENCES SISTEMAS (ID),
    CONSTRAINT SCHEDULERS_USUARIO_FK FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS (ID)
);

-- Sequência manual
CREATE SEQUENCE SCHEDULERS_SEQ START WITH 1 INCREMENT BY 1;

--Gatilho
CREATE OR REPLACE TRIGGER SCHEDULERS_TRG_ID
BEFORE INSERT ON SCHEDULERS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SCHEDULERS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
